In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('data_tugas.csv',sep=';')
data.head()

,CO_GT,konsentrasi_CO,konsentrasi_NMHC,konsentrasi_C6H6,konsentrasi_NMHC,konsentrasi_NO,konsentrasi_Nox,konsentrasi_NO2,konsentrasi_NO2,konsentrasi_O3,konsentrasi_RH,konsentrasi_AH
0,3.0,1.360,150.0,12,1.046,166.0,1.056,113.0,1.692,1.268,49,1
1,2.0,1.292,112.0,9,955.000,103.0,1.174,92.0,1.559,972.000,48,1
2,2.0,1.402,88.0,9,939.000,131.0,1.140,114.0,1.555,1.074,54,1
3,2.0,1.376,80.0,9,948.000,172.0,1.092,122.0,1.584,1.203,60,1
4,2.0,NaN,51.0,7,836.000,131.0,1.205,116.0,1.490,1.110,60,1

In [3]:
data.describe()

,CO_GT,konsentrasi_CO,konsentrasi_NMHC,konsentrasi_C6H6,konsentrasi_NMHC,konsentrasi_NO,konsentrasi_Nox,konsentrasi_NO2,konsentrasi_NO2,konsentrasi_O3,konsentrasi_RH,konsentrasi_AH
count,9339.000000,9339.000000,9353.000000,9357.000000,9339.000000,9350.000000,9344.000000,9338.000000,9340.000000,9348.000000,9357.000000,9357.000000
mean,-34.186315,316.634587,-159.547264,1.914289,453.079852,159.061906,544.627504,58.259584,83.804610,366.323654,39.529229,-6.831891
std,77.702340,439.097535,137.361448,41.390446,402.889958,241.634776,356.936496,126.921876,272.915634,392.986541,51.224668,38.979027
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,1.000000,1.116500,-200.000000,4.000000,1.217000,47.000000,365.750000,53.000000,1.310000,1.284750,34.000000,1.000000
50%,2.000000,1.346000,-200.000000,8.000000,620.000000,138.000000,668.000000,96.000000,1.531000,368.500000,49.000000,1.000000
75%,3.000000,862.500000,-200.000000,14.000000,814.000000,278.000000,819.000000,133.000000,1.793250,757.000000,62.000000,1.000000
max,12.000000,999.000000,974.000000,64.000000,999.000000,999.000000,999.000000,340.000000,999.000000,999.000000,89.000000,2.000000

In [4]:
np.sum(data.isnull())

CO_GT                18
konsentrasi_CO       18
konsentrasi_NMHC      4
konsentrasi_C6H6      0
konsentrasi_NMHC     18
konsentrasi_NO        7
konsentrasi_Nox      13
konsentrasi_NO2      19
konsentrasi_NO2      17
konsentrasi_O3        9
konsentrasi_RH        0
konsentrasi_AH        0
dtype: int64

In [5]:
data['CO_GT ']=data['CO_GT '].fillna(-34.186315)
data['konsentrasi_CO ']=data['konsentrasi_CO '].fillna(316.634587)
data['konsentrasi_NMHC']=data['konsentrasi_NMHC'].fillna(-159.547264)
data['konsentrasi_NO']=data['konsentrasi_NO'].fillna(159.061906)
data['konsentrasi_NMHC ']=data['konsentrasi_NMHC '].fillna(453.079852)
data['konsentrasi_Nox']=data['konsentrasi_Nox'].fillna(544.627504)
data['konsentrasi_NO2']=data['konsentrasi_NO2'].fillna(58.259584)
data['konsentrasi_NO2 ']=data['konsentrasi_NO2 '].fillna(83.804610)
data['konsentrasi_O3']=data['konsentrasi_O3'].fillna(366.323654)
np.sum(data.isnull())

CO_GT                0
konsentrasi_CO       0
konsentrasi_NMHC     0
konsentrasi_C6H6     0
konsentrasi_NMHC     0
konsentrasi_NO       0
konsentrasi_Nox      0
konsentrasi_NO2      0
konsentrasi_NO2      0
konsentrasi_O3       0
konsentrasi_RH       0
konsentrasi_AH       0
dtype: int64

In [6]:
from scipy import stats
z= np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data=data[(z<3).all(axis=1)]
print(data.shape)

[[0.47906057 0.71873591 2.25412593 ... 0.92942339 0.18489679 0.2009365 ]
 [0.46617786 0.71889093 1.97740959 ... 1.54203819 0.1653739  0.2009365 ]
 [0.46617786 0.71864017 1.80264137 ... 0.92991731 0.28251123 0.2009365 ]
 ...
 [0.46617786 0.71923289 0.29457719 ... 0.92987148 0.42031273 0.2009365 ]
 [0.46617786 0.71954977 0.29457719 ... 1.02775079 0.49840428 0.2009365 ]
 [0.46617786 0.71939475 0.29457719 ... 1.14486574 0.51792717 0.2009365 ]]
(8231, 12)